# Generated by Django 4.0.4 on 2022-05-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['albumName'],
            },
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=100)),
                ('genreDescription', models.TextField()),
            ],
            options={
                'ordering': ['genreName'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadataName', models.CharField(max_length=100)),
                ('metadataDescription', models.TextField()),
            ],
            options={
                'ordering': ['metadataName'],
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['needName'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPic', models.TextField()),
                ('userAbout', models.TextField()),
                ('userSpotPlay', models.TextField()),
            ],
            options={
                'ordering': ['userName'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackName', models.CharField(max_length=100)),
                ('trackDescription', models.TextField()),
                ('trackAudio', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='colab.album')),
                ('collabs', models.ManyToManyField(related_name='collabs', to='colab.collab')),
                ('genres', models.ManyToManyField(related_name='genres', to='colab.genre')),
                ('metadata', models.ManyToManyField(related_name='metadata', to='colab.metadata')),
                ('needs', models.ManyToManyField(related_name='needs', to='colab.need')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='colab.user')),
            ],
            options={
                'ordering': ['trackName'],
            },
        ),
        migrations.AddField(
            model_name='collab',
            name='users',
            field=models.ManyToManyField(related_name='collabs', to='colab.user'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='colab.user'),
        ),
    ]
