# Generated by Django 4.0.4 on 2022-05-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadataDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='colab.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='collabs',
            field=models.ManyToManyField(blank=True, related_name='collabs', to='colab.collab'),
        ),
        migrations.AlterField(
            model_name='track',
            name='trackDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userAbout',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userSpotPlay',
            field=models.TextField(blank=True),
        ),
    ]
