# Generated by Django 4.0.4 on 2022-05-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_alter_genre_genredescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='colab.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='collabs',
            field=models.ManyToManyField(blank=True, null=True, related_name='collabs', to='colab.collab'),
        ),
    ]
