# Generated by Django 4.0.4 on 2022-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_alter_track_album_alter_track_collabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='collabs',
        ),
        migrations.AddField(
            model_name='collab',
            name='tracks',
            field=models.ManyToManyField(related_name='collabs', to='colab.track'),
        ),
    ]
