# Generated by Django 4.0.4 on 2022-05-06 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0004_remove_track_collabs_collab_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='tracks',
        ),
        migrations.AddField(
            model_name='collab',
            name='track',
            field=models.ForeignKey(default=3, on_delete=models.SET(
                'track deleted'), related_name='collabs', to='colab.track'),
            preserve_default=False,
        ),
    ]
