# Generated by Django 4.0.4 on 2022-05-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0005_remove_collab_tracks_collab_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(related_name='tracks', to='colab.genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='metadata',
            field=models.ManyToManyField(related_name='tracks', to='colab.metadata'),
        ),
        migrations.AlterField(
            model_name='track',
            name='needs',
            field=models.ManyToManyField(related_name='tracks', to='colab.need'),
        ),
    ]
