# Generated by Django 4.0.4 on 2022-05-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0006_alter_track_genres_alter_track_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collabs', to='colab.track'),
        ),
    ]
