# Generated by Django 4.0.4 on 2022-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0007_alter_collab_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='collabComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='userCollabCount',
            field=models.IntegerField(default=0),
        ),
    ]
